export enum MSG_KEY {
    ROUND_PER_START = 'ROUND_PER_START',
    ROUND_START_BET = 'ROUND_START_BET',
    DEFAULT_MESSAGE = 'DEFAULT_MESSAGE',
    PLAYER_BET_SUCCESS = 'PLAYER_BET_SUCCESS',
    PLAYER_BET_REJECTED = 'PLAYER_BET_REJECTED',
    ROUND_STOP_BET = 'ROUND_STOP_BET',
    ROUND_PER_DRAW = 'ROUND_PER_DRAW',
    ROUND_DRAW_RESULT = 'ROUND_DRAW_RESULT',
    ROUND_START_PAYOUT = 'ROUND_START_PAYOUT',
    ROUND_RESET = 'ROUND_RESET'
}
